##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Generate Containerized Node.js Application
author: cloudopsworks
description: |
  This action generates a containerized Node.js application.
  It is intended to be used in a CI/CD pipeline
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  semver:
    description: 'The semver version to use for the build'
    required: true
  node_version:
    description: 'The Node.js version to use for the build'
    required: true
  node_dist:
    description: 'The Node.js distribution to use for the build'
    required: true
  node_image_variant:
    description: 'The Node.js image variant to use for the build'
    required: true
  environment:
    description: 'The environment to use for the build'
    required: true
  is_release:
    description: 'The release flag'
    required: true
  default_registry_address:
    description: 'The default registry'
    required: true
  project_key:
    description: 'The project name key'
    required: true
  project_owner:
    description: 'The project owner'
    required: true
  front_end:
    description: 'The front end flag'
    required: true
  observability_enabled:
    description: 'The observability flag'
    required: false
    default: 'false'
  observability_agent:
    description: 'The observability agent'
    required: false
    default: 'xray'

runs:
  using: 'composite'
  steps:
    # Recover the docker_registry value from the environment file
    - name: Get Docker Registry value if set into the ENV file
      id: docker_registry
      shell: bash
      env:
        INPUTS_DEFAULT_REGISTRY_ADDRESS: ${{ inputs.default_registry_address }}
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
        INPUTS_ENVIRONMENT: ${{ inputs.environment }}
      run: |
        RET=$(yq -I=0 ".container_registry // strenv(INPUTS_DEFAULT_REGISTRY_ADDRESS)" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-${INPUTS_ENVIRONMENT}.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Docker Inline Setting
      id: docker_inline
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 ".docker_inline // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Docker Arguments
      id: docker_args_global
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 ".docker_args // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Docker Arguments for ${{ inputs.environment }}
      id: docker_args_env
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
        INPUTS_ENVIRONMENT: ${{ inputs.environment }}
      run: |
        RET=$(yq e -I=0 ".docker_args // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-${INPUTS_ENVIRONMENT}.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Custom Run Command
      id: custom_run_command
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 ".custom_run_command // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Custom Usergroup
      id: custom_usergroup
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 ".custom_usergroup // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Copy Dockerfile Front-End App
      if: ${{ inputs.front_end == 'true' }}
      shell: bash
      env:
        INPUTS_BLUEPRINT_PATH: ${{ inputs.blueprint_path }}
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        cp -pf "${INPUTS_BLUEPRINT_PATH}/ci/container/blueprints/frontend/"* "${INPUTS_SOURCE_PATH}/"
        cp -pf "${INPUTS_BLUEPRINT_PATH}/ci/container/blueprints/frontend/.dockerignore" "${INPUTS_SOURCE_PATH}/"

    - name: Get default config_map mount point for environment
      id: config_map_mount_point
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
        INPUTS_ENVIRONMENT: ${{ inputs.environment }}
      run: |
        RET=$(yq e -I=0 ".config_map.mount_point // \"/app/configmap\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-${INPUTS_ENVIRONMENT}.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Copy Dockerfile Node.js App
      if: ${{ inputs.front_end != 'true' }}
      shell: bash
      env:
        INPUTS_BLUEPRINT_PATH: ${{ inputs.blueprint_path }}
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        cp -pf "${INPUTS_BLUEPRINT_PATH}/ci/container/blueprints/nodejs/"* "${INPUTS_SOURCE_PATH}/"
        cp -pf "${INPUTS_BLUEPRINT_PATH}/ci/container/blueprints/nodejs/.dockerignore" "${INPUTS_SOURCE_PATH}/"

    - name: APM Arguments setup
      id: apm_args
      shell: bash
      if: ${{ inputs.observability_enabled == 'true' }}
      env:
        INPUTS_OBSERVABILITY_AGENT: ${{ inputs.observability_agent }}
      run: |
        case "${INPUTS_OBSERVABILITY_AGENT}" in
          xray)
            echo "result=APM_OPTS=--require @aws/aws-distro-opentelemetry-node-autoinstrumentation/register" >> $GITHUB_OUTPUT
            ;;
          datadog)
            echo "result=APM_OPTS=(DATADOG)" >> $GITHUB_OUTPUT
            ;;
        esac

    # for non front end projects nodejs version is set by parameter, defaults to 20
    - name: Set output with node Version
      if: ${{ inputs.front_end != 'true' }}
      id: docker_image_name
      shell: bash
      env:
        INPUTS_NODE_VERSION: ${{ inputs.node_version }}
        INPUTS_NODE_IMAGE_VARIANT: ${{ inputs.node_image_variant }}
      run: |
        if [ "${INPUTS_NODE_VERSION}" != "" ] ; then
          case "${INPUTS_NODE_IMAGE_VARIANT}" in
            alpine*)
              echo "result=IMAGE_NAME=node:${INPUTS_NODE_VERSION}-${INPUTS_NODE_IMAGE_VARIANT}" >> $GITHUB_OUTPUT
              ;;
            bookworn*)
              echo "result=IMAGE_NAME=node:${INPUTS_NODE_VERSION}-${INPUTS_NODE_IMAGE_VARIANT}" >> $GITHUB_OUTPUT
              ;;
            bullseye*)
              echo "result=IMAGE_NAME=node:${INPUTS_NODE_VERSION}-${INPUTS_NODE_IMAGE_VARIANT}" >> $GITHUB_OUTPUT
              ;;
            current*)
              echo "result=IMAGE_NAME=node:${INPUTS_NODE_VERSION}-${INPUTS_NODE_IMAGE_VARIANT}" >> $GITHUB_OUTPUT
              ;;
            slim)
              echo "result=IMAGE_NAME=node:${INPUTS_NODE_VERSION}-${INPUTS_NODE_IMAGE_VARIANT}" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "result=IMAGE_NAME=node:${INPUTS_NODE_VERSION}" >> $GITHUB_OUTPUT
              ;;
          esac
        fi

    # if custom_run_command is non empty then need to override the startup.sh scripts with new content, write the file in-place
    - name: Set custom run command
      working-directory: ${{ inputs.source_path }}
      if: ${{ steps.custom_run_command.outputs.result != '' }}
      shell: bash
      run: |
        echo "Creation of custom startup.sh script..."
        cat > ./startup.sh << EOF
        #!/bin/sh
        
        # Startup the nodejs Server (custom command)
        cd /app/webapp
        $CUSTOM_RUN_COMMAND
        EOF
        cat ./startup.sh
      env:
        CUSTOM_RUN_COMMAND: ${STEPS_CUSTOM_RUN_COMMAND_RESULT}

        STEPS_CUSTOM_RUN_COMMAND_RESULT: ${STEPS_CUSTOM_RUN_COMMAND_RESULT}
    # Run Generalized Docker Build & Upload Artifact
    - name: Generalized Docker Build
      uses: ./bp/ci/container/build
      with:
        semver: ${{ inputs.semver }}
        docker_registry: ${{ steps.docker_registry.outputs.result }}
        docker_inline: ${{ steps.docker_inline.outputs.result }}
        docker_image_name: ${{ steps.docker_image_name.outputs.result }}
        docker_args: ${{ steps.docker_args_env.outputs.result == '' && steps.docker_args_global.outputs.result || steps.docker_args_env.outputs.result }}
        apm_args: ${{ inputs.observability_enabled == 'true' && steps.apm_args.outputs.result || '' }}
        environment: ${{ inputs.environment }}
        project_key: ${{ inputs.project_key }}
        project_owner: ${{ inputs.project_owner }}
        custom_usergroup: ${{ steps.custom_usergroup.outputs.result }}
        front_end: ${{ inputs.front_end }}
        is_release: ${{ inputs.is_release }}
