##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Generate Containerized Python Application
author: cloudopsworks
description: Generate a containerized Python application
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  semver:
    description: 'The semver version to use for the build'
    required: true
  python_version:
    description: 'The Python version to use for the build'
    required: true
  python_dist:
    description: 'The Python distribution to use for the build'
    required: true
  python_image_variant:
    description: 'The Python image variant to use for the build'
    required: true
  environment:
    description: 'The environment to use for the build'
    required: true
  is_release:
    description: 'The release flag'
    required: true
  default_registry_address:
    description: 'The default registry'
    required: true
  project_key:
    description: 'The project name key'
    required: true
  project_owner:
    description: 'The project owner'
    required: true

runs:
  using: 'composite'
  steps:
    # Recover the docker_registry value from the environment file
    - name: Get Docker Registry value if set into the ENV file
      id: docker_registry
      shell: bash
      env:
        INPUTS_DEFAULT_REGISTRY_ADDRESS: ${{ inputs.default_registry_address }}
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
        INPUTS_ENVIRONMENT: ${{ inputs.environment }}
      run: |
        RET=$(yq -I=0 ".container_registry // strenv(INPUTS_DEFAULT_REGISTRY_ADDRESS)" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-${INPUTS_ENVIRONMENT}.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Docker Inline Setting
      id: docker_inline
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 ".docker_inline // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Docker Arguments
      id: docker_args_global
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 ".docker_args // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Docker Arguments for ${{ inputs.environment }}
      id: docker_args_env
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
        INPUTS_ENVIRONMENT: ${{ inputs.environment }}
      run: |
        RET=$(yq e -I=0 ".docker_args // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-${INPUTS_ENVIRONMENT}.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Custom Run Command
      id: custom_run_command
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 ".custom_run_command // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Custom Usergroup
      id: custom_usergroup
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 ".custom_usergroup // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Copy Dockerfile Python App
      shell: bash
      env:
        INPUTS_BLUEPRINT_PATH: ${{ inputs.blueprint_path }}
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        cp -pf "${INPUTS_BLUEPRINT_PATH}/ci/container/blueprints/python/"* "${INPUTS_SOURCE_PATH}/"
        cp -pf "${INPUTS_BLUEPRINT_PATH}/ci/container/blueprints/python/.dockerignore" "${INPUTS_SOURCE_PATH}/"

    - name: Dockerfile Python Specific Injection
      working-directory: ${{ inputs.source_path }}
      shell: bash
      env:
        INPUTS_PYTHON_VERSION: ${{ inputs.python_version }}
        INPUTS_DOCKER_INLINE: ${{ inputs.docker_inline }}
      run: |
        echo "::group::Injecting Python content in Dockerfile..."
        DOCKERFILE=Dockerfile
        TEMP_FILE=$(mktemp)
        INJECTION_POINT="#<PYTHON-INJECTION-POINT>"
        while IFS= read -r line; do
          if [[ "$line" =~ $INJECTION_POINT ]]; then
            # Run pip install with requirements.txt
            echo "RUN pip install -r /app/webapp/requirements.txt --target /app/webapp --python-version ${INPUTS_PYTHON_VERSION} --implementation cp --only-binary=:all: --upgrade"
            echo "${INPUTS_DOCKER_INLINE}"
          else
            # Print the current line
            echo "$line"
          fi
        done < "$DOCKERFILE" > "$TEMP_FILE"
        mv "$TEMP_FILE" "$DOCKERFILE"
        cat "$DOCKERFILE"
        echo "::endgroup::"

    # Python version image settings (adopt is deprecated)
    - name: Set output with Python Version
      id: docker_image_name
      shell: bash
      env:
        INPUTS_PYTHON_VERSION: ${{ inputs.python_version }}
        INPUTS_PYTHON_IMAGE_VARIANT: ${{ inputs.python_image_variant }}
      run: |
        if [ "${INPUTS_PYTHON_VERSION}" != "" ] ; then
          if [ "${INPUTS_PYTHON_IMAGE_VARIANT}" != "" ] ; then
            echo "result=IMAGE_NAME=python:${INPUTS_PYTHON_VERSION}-${INPUTS_PYTHON_IMAGE_VARIANT}" >> $GITHUB_OUTPUT
          else
            echo "result=IMAGE_NAME=python:${INPUTS_PYTHON_VERSION}-alpine" >> $GITHUB_OUTPUT
          fi
        fi

    # if custom_run_command is non empty then need to override the startup.sh scripts with new content, write the file in-place
    - name: Set custom run command
      working-directory: ${{ inputs.source_path }}
      if: ${{ steps.custom_run_command.outputs.result != '' }}
      shell: bash
      run: |
        echo "Creation of custom startup.sh script..."
        cat > ./startup.sh << EOF
        #!/bin/sh
        
        # Startup the Python App (custom command)
        cd /app/webapp
        $CUSTOM_RUN_COMMAND
        EOF
        cat ./startup.sh
      env:
        CUSTOM_RUN_COMMAND: ${{ steps.custom_run_command.outputs.result }}

    # Run Generalized Docker Build & Upload Artifact
    - name: Generalized Docker Build
      uses: ./bp/ci/container/build
      with:
        semver: ${{ inputs.semver }}
        docker_registry: ${{ steps.docker_registry.outputs.result }}
        docker_inline: ${{ steps.docker_inline.outputs.result }}
        docker_image_name: ${{ steps.docker_image_name.outputs.result }}
        docker_args: ${{ steps.docker_args_env.outputs.result == '' && steps.docker_args_global.outputs.result || steps.docker_args_env.outputs.result }}
        environment: ${{ inputs.environment }}
        project_key: ${{ inputs.project_key }}
        project_owner: ${{ inputs.project_owner }}
        custom_usergroup: ${{ steps.custom_usergroup.outputs.result }}
        is_release: ${{ inputs.is_release }}
