##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Deploy Rust Component
author: cloudopsworks
description: Deploy Rust component to Go repository
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  artifacts_name:
    description: 'The name of the artifacts to save'
    required: false
    default: 'build_artifacts'
  sources_artifacts_name:
    description: 'The name of the sources to save'
    required: false
    default: 'source_artifacts'
  bot_user:
    description: 'The bot user to use for the build'
    required: true
  token:
    description: 'The github token to use for the build'
    required: true

runs:
  using: 'composite'
  steps:
    # Get if this is a library project
    - name: Get pipeline preview enabled
      id: is_library
      uses: mikefarah/yq@master
      with:
        cmd: yq e '.isLibrary and true' ./${{ inputs.source_path }}/.github/vars/inputs-global.yaml

    # Get from global inputs the custom Go Options
    - name: Get Go options
      id: build_opts
      uses: mikefarah/yq@master
      with:
        cmd: yq e -I=0 '.build_options // ""' ./${{ inputs.source_path }}/.github/vars/inputs-global.yaml

    # Deploy release to Go Repository (defaults to Github repo)
    - name: Deploy to Go Repo
      if: ${{ steps.is_library.outputs.result == 'true' }}
      working-directory: ${{ inputs.source_path }}
      shell: bash
      run: |
        echo "::group::Go Deploy to Repo"
        echo "NOT SUPPORTED YET"
        echo "::endgroup::"
      env:
        GITHUB_ACTOR: ${{ inputs.bot_user }}
        GITHUB_TOKEN: ${{ inputs.token }}
