##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Datadog Observability deployment setup for HELM
author: cloudopsworks
description: Datadog Observability deployment setup for HELM chart
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  cloud:
    description: 'The cloud'
    required: true
  release_name:
    description: 'The release name'
    required: true
  release_version:
    description: 'The release version'
    required: true
  project_key:
    description: 'The package name'
    required: true
  deployment_name:
    description: 'The deployment name'
    required: true
  environment:
    description: 'The environment'
    required: true

runs:
  using: 'composite'
  steps:
    - name: DD_TAGS
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: dd_tags
      shell: bash
      run: |
        result=$(yq e -I=0 '.observability.config.tags // ""' inputs-global.yaml)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: DD_LOGS_ENABLED
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: dd_logs_enabled
      shell: bash
      run: |
        result=$(yq e -I=0 '.observability.config.logs_enabled // "true"' inputs-global.yaml)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: DD_APM_ENABLED
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: dd_apm_enabled
      shell: bash
      run: |
        result=$(yq e -I=0 '.observability.config.apm_enabled // "true"' inputs-global.yaml)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: DD_APM_NON_LOCAL_TRAFFIC
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: dd_apm_non_local_traffic
      shell: bash
      run: |
        result=$(yq e -I=0 '.observability.config.apm_non_local_traffic // "true"' inputs-global.yaml)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: DD_LOGS_INJECTION
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: dd_logs_injection
      shell: bash
      run: |
        result=$(yq e -I=0 '.observability.config.logs_injection // "true"' inputs-global.yaml)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: dd_logs_config_container_collect_all
      shell: bash
      run: |
        result=$(yq e -I=0 '.observability.config.logs_config_container_collect_all // true' inputs-global.yaml)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: DD_CONTAINER_EXCLUDE_LOGS
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: dd_container_exclude_logs
      shell: bash
      run: |
        result=$(yq e -I=0 '.observability.config.container_exclude_logs // ""' inputs-global.yaml)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: DD_TRACE_DEBUG
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: dd_trace_debug
      shell: bash
      run: |
        result=$(yq e -I=0 '.observability.config.trace_debug // false' inputs-global.yaml)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: DD_DBM_PROPAGATION_MODE
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: dd_dbm_propagation_mode
      shell: bash
      run: |
        result=$(yq e -I=0 '.observability.config.dbm_propagation_mode // "full"' inputs-global.yaml)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: dd_dogstatsd_non_local_traffic
      shell: bash
      run: |
        result=$(yq e -I=0 '.observability.config.dogstatsd_non_local_traffic // "true"' inputs-global.yaml)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: DD_HTTP_CLIENT_ERROR_STATUSES
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: dd_http_client_error_statuses
      shell: bash
      run: |
        result=$(yq e -I=0 '.observability.config.http_client_error_statuses // "400,401,403,404,405,409,410,429,500,501,502,503,504,505"' inputs-global.yaml)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: DD_HTTP_SERVER_ERROR_STATUSES
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: dd_http_server_error_statuses
      shell: bash
      run: |
        result=$(yq e -I=0 '.observability.config.http_server_error_statuses // "500,502,503,504,505"' inputs-global.yaml)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: Datadog variable Injection
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: datadog_inject
      shell: bash
      env:
        INPUTS_ENVIRONMENT: ${{ inputs.environment }}
        INPUTS_RELEASE_NAME: ${{ inputs.release_name }}
        INPUTS_RELEASE_VERSION: ${{ inputs.release_version }}
        STEPS_DD_LOGS_ENABLED_RESULT: ${{ steps.dd_logs_enabled.outputs.result }}
        STEPS_DD_APM_ENABLED_RESULT: ${{ steps.dd_apm_enabled.outputs.result }}
        STEPS_DD_APM_NON_LOCAL_TRAFFIC_RESULT: ${{ steps.dd_apm_non_local_traffic.outputs.result }}
        STEPS_DD_LOGS_INJECTION_RESULT: ${{ steps.dd_logs_injection.outputs.result }}
        STEPS_DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL_RESULT: ${{ steps.dd_logs_config_container_collect_all.outputs.result }}
        STEPS_DD_CONTAINER_EXCLUDE_LOGS_RESULT: ${{ steps.dd_container_exclude_logs.outputs.result }}
        STEPS_DD_TRACE_DEBUG_RESULT: ${{ steps.dd_trace_debug.outputs.result }}
        STEPS_DD_DBM_PROPAGATION_MODE_RESULT: ${{ steps.dd_dbm_propagation_mode.outputs.result }}
        STEPS_DD_DOGSTATSD_NON_LOCAL_TRAFFIC_RESULT: ${{ steps.dd_dogstatsd_non_local_traffic.outputs.result }}
        STEPS_DD_HTTP_CLIENT_ERROR_STATUSES_RESULT: ${{ steps.dd_http_client_error_statuses.outputs.result }}
        STEPS_DD_HTTP_SERVER_ERROR_STATUSES_RESULT: ${{ steps.dd_http_server_error_statuses.outputs.result }}
      run: |
        echo "::group::Datadog variable Injection"
        DD_ENV="${INPUTS_ENVIRONMENT}" yq e -i ".env += {\"name\":\"DD_ENV\",\"value\":strenv(DD_ENV)}" helm-values.yaml
        DD_SERVICE="${INPUTS_RELEASE_NAME}" yq e -i ".env += {\"name\":\"DD_SERVICE\",\"value\":strenv(DD_SERVICE)}" helm-values.yaml
        DD_VERSION="${INPUTS_RELEASE_VERSION}" yq e -i ".env += {\"name\":\"DD_VERSION\",\"value\":strenv(DD_VERSION)}" helm-values.yaml
        DD_LOGS_ENABLED="${STEPS_DD_LOGS_ENABLED_RESULT}" yq e -i ".env += {\"name\":\"DD_LOGS_ENABLED\",\"value\":strenv(DD_LOGS_ENABLED)}" helm-values.yaml
        DD_APM_ENABLED="${STEPS_DD_APM_ENABLED_RESULT}" yq e -i ".env += {\"name\":\"DD_APM_ENABLED\",\"value\":strenv(DD_APM_ENABLED)}" helm-values.yaml
        DD_APM_NON_LOCAL_TRAFFIC="${STEPS_DD_APM_NON_LOCAL_TRAFFIC_RESULT}" yq e -i ".env += {\"name\":\"DD_APM_NON_LOCAL_TRAFFIC\",\"value\":strenv(DD_APM_NON_LOCAL_TRAFFIC)}" helm-values.yaml
        DD_LOGS_INJECTION="${STEPS_DD_LOGS_INJECTION_RESULT}" yq e -i ".env += {\"name\":\"DD_LOGS_INJECTION\",\"value\":strenv(DD_LOGS_INJECTION)}" helm-values.yaml
        DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL="${STEPS_DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL_RESULT}" yq e -i ".env += {\"name\":\"DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL\",\"value\":strenv(DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL)}" helm-values.yaml
        DD_CONTAINER_EXCLUDE_LOGS="${STEPS_DD_CONTAINER_EXCLUDE_LOGS_RESULT}" yq e -i ".env += {\"name\":\"DD_CONTAINER_EXCLUDE_LOGS\",\"value\":strenv(DD_CONTAINER_EXCLUDE_LOGS)}" helm-values.yaml
        DD_TRACE_DEBUG="${STEPS_DD_TRACE_DEBUG_RESULT}" yq e -i ".env += {\"name\":\"DD_TRACE_DEBUG\",\"value\":strenv(DD_TRACE_DEBUG)}" helm-values.yaml
        DD_DBM_PROPAGATION_MODE="${STEPS_DD_DBM_PROPAGATION_MODE_RESULT}" yq e -i ".env += {\"name\":\"DD_DBM_PROPAGATION_MODE\",\"value\":strenv(DD_DBM_PROPAGATION_MODE)}" helm-values.yaml
        DD_DOGSTATSD_NON_LOCAL_TRAFFIC="${STEPS_DD_DOGSTATSD_NON_LOCAL_TRAFFIC_RESULT}" yq e -i ".env += {\"name\":\"DD_DOGSTATSD_NON_LOCAL_TRAFFIC\",\"value\":strenv(DD_DOGSTATSD_NON_LOCAL_TRAFFIC)}" helm-values.yaml
        DD_HTTP_CLIENT_ERROR_STATUSES="${STEPS_DD_HTTP_CLIENT_ERROR_STATUSES_RESULT}" yq e -i ".env += {\"name\":\"DD_HTTP_CLIENT_ERROR_STATUSES\",\"value\":strenv(DD_HTTP_CLIENT_ERROR_STATUSES)}" helm-values.yaml
        DD_HTTP_SERVER_ERROR_STATUSES="${STEPS_DD_HTTP_SERVER_ERROR_STATUSES_RESULT}" yq e -i ".env += {\"name\":\"DD_HTTP_SERVER_ERROR_STATUSES\",\"value\":strenv(DD_HTTP_SERVER_ERROR_STATUSES)}" helm-values.yaml
        echo "::endgroup::"
