##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Deploy Preview Application AWS
author: cloudopsworks
description: Deploy Preview Application AWS
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  token:
    description: 'The GitHub token'
    required: true
  cloud_type:
    description: 'The cloud type'
    required: true
  aws_region:
    description: 'The AWS region'
    required: true
  aws_sts_role_arn:
    description: 'The AWS STS Role ARN'
    required: true
  aws_access_key_id:
    description: 'The AWS access key ID'
    required: true
  aws_secret_access_key:
    description: 'The AWS secret access key'
    required: true
  terraform_state_conf:
    description: 'The Terraform state configuration'
    required: true
  unlock:
    description: 'Unlock the state'
    required: false
    default: 'false'
  lock_id:
    description: 'The lock ID'
    required: false
    default: ''
  destroy:
    description: 'Destroy the state'
    required: false
    default: 'false'
  release_name:
    description: 'The release name'
    required: true
  release_version:
    description: 'The release version'
    required: true
  qualifier:
    description: 'The release qualifier'
    required: false
    default: ''
  project_key:
    description: 'The package name'
    required: true
  deployment_name:
    description: 'The deployment name'
    required: true
  environment:
    description: 'The environment'
    required: true
  artifacts_name:
    description: 'The name of the artifacts to save'
    required: false
    default: 'build_artifacts'
  container_registry:
    description: 'The container registry'
    required: true
  pull_request_name:
    description: 'The pull request name'
    required: true
  cluster_name:
    description: 'The Kubernetes cluster name'
    required: true
  rancher_project_id:
    description: 'The Rancher project ID'
    required: true
  project_owner:
    description: 'The project owner'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get Preview Domain
      id: preview_domain
      working-directory: ${{ inputs.source_path }}
      shell: bash
      run: |
        VAL=$(yq e '.preview.domain' .cloudopsworks/vars/inputs-global.yaml)
        echo "result=$VAL" >> $GITHUB_OUTPUT

    - name: IAC Setup
      uses: cloudopsworks/blueprints/cd/deploy/common/iac@v5.10
      with:
        source_path: ${{ inputs.source_path }}
        blueprint_path: ${{ inputs.blueprint_path }}
        token: ${{ inputs.token }}

    - name: Copy configurations
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
        INPUTS_BLUEPRINT_PATH: ${{ inputs.blueprint_path }}
        INPUTS_CONTAINER_REGISTRY: ${{ inputs.container_registry }}
        INPUTS_PROJECT_OWNER: ${{ inputs.project_owner }}
        INPUTS_PROJECT_KEY: ${{ inputs.project_key }}
        INPUTS_RELEASE_NAME: ${{ inputs.release_name }}
        INPUTS_PULL_REQUEST_NAME: ${{ inputs.pull_request_name }}
        STEPS_PREVIEW_DOMAIN_RESULT: ${{ steps.preview_domain.outputs.result }}
        INPUTS_RANCHER_PROJECT_ID: ${{ inputs.rancher_project_id }}
        INPUTS_CLUSTER_NAME: ${{ inputs.cluster_name }}
      run: |
        cp -pf "${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/preview/inputs.yaml" "${INPUTS_BLUEPRINT_PATH}/terraform/azure/kubernetes/inputs.yaml"
        cp -pf "${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml" "${INPUTS_BLUEPRINT_PATH}/terraform/azure/kubernetes/inputs-global.yaml"
        inputs_file="${INPUTS_BLUEPRINT_PATH}/terraform/azure/kubernetes/inputs.yaml"
        IMAGE_REPOSITORY="${INPUTS_CONTAINER_REGISTRY}/${INPUTS_PROJECT_OWNER}/${INPUTS_PROJECT_KEY}"
        INGRESS_HOST="${INPUTS_RELEASE_NAME}-${INPUTS_PULL_REQUEST_NAME}.${STEPS_PREVIEW_DOMAIN_RESULT}"
        TLS_SECRET_NAME="${INPUTS_RELEASE_NAME}-${INPUTS_PULL_REQUEST_NAME}-tls"
        NAMESPACE="${INPUTS_RELEASE_NAME}-${INPUTS_PULL_REQUEST_NAME}"
        export IMAGE_REPOSITORY INGRESS_HOST TLS_SECRET_NAME NAMESPACE
        yq e ".helm_values_overrides += {\"image.repository\": strenv(IMAGE_REPOSITORY)}" -i "${inputs_file}"
        yq e ".helm_values_overrides += {\"ingress.host\": strenv(INGRESS_HOST)}" -i "${inputs_file}"
        yq e ".helm_values_overrides += {\"ingress.rules[0].host\": strenv(INGRESS_HOST)}" -i "${inputs_file}"
        yq e ".helm_values_overrides += {\"ingress.annotations.cert-manager\\.io/cluster-issuer\":\"letsencrypt-prod\"}" -i "${inputs_file}"
        yq e ".helm_values_overrides += {\"ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/ssl-redirect\":\"true\"}" -i "${inputs_file}"
        yq e ".helm_values_overrides += {\"ingress.tls.secretName\": strenv(TLS_SECRET_NAME)}" -i "${inputs_file}"
        yq e ".helm_values_overrides += {\"ingress.tls.enabled\": true}" -i "${inputs_file}"
        RANCHER_PROJECT_ID="${INPUTS_RANCHER_PROJECT_ID}" yq e ".namespace_annotations += {\"field.cattle.io/projectId\": strenv(RANCHER_PROJECT_ID)}" -i "${inputs_file}"
        CONTAINER_REGISTRY="${INPUTS_CONTAINER_REGISTRY}" yq e ".container_registry = strenv(CONTAINER_REGISTRY)" -i "${inputs_file}"
        CLUSTER_NAME="${INPUTS_CLUSTER_NAME}" yq e ".cluster_name = strenv(CLUSTER_NAME)" -i "${inputs_file}"
        yq e ".namespace = strenv(NAMESPACE)" -i "${inputs_file}"
        yq e ".create_namespace = true" -i "${inputs_file}"

    - name: Copy Values Bundle
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
        INPUTS_BLUEPRINT_PATH: ${{ inputs.blueprint_path }}
      run: |
        cp -pf "${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/preview/values.yaml" "${INPUTS_BLUEPRINT_PATH}/terraform/azure/kubernetes/helm-values.yaml"
        mkdir -p "${INPUTS_BLUEPRINT_PATH}/terraform/azure/kubernetes/values/"
        if [ -d "${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/preview/values" ]; then
          cp -pfR "${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/preview/values/" "${INPUTS_BLUEPRINT_PATH}/terraform/azure/kubernetes/"
        else
          echo "No values found for ${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/preview/values, skipping..."
          touch "${INPUTS_BLUEPRINT_PATH}/terraform/azure/kubernetes/values/.empty"
        fi

    - name: Generate release.yaml
      working-directory: ${{ inputs.blueprint_path }}/terraform/azure/kubernetes
      shell: bash
      env:
        INPUTS_PROJECT_KEY: ${{ inputs.project_key }}
        INPUTS_RELEASE_VERSION: ${{ inputs.release_version }}
      run: |
        printf "%s\n" \
          "release:" \
          "  name: preview" \
          "  source:" \
          "    name: ${INPUTS_PROJECT_KEY}" \
          "    version: ${INPUTS_RELEASE_VERSION}" \
          > release.yaml

    - name: Generate Global Inputs global-inputs.yaml
      working-directory: ${{ inputs.blueprint_path }}/terraform/azure
      shell: bash
      env:
        INPUTS_PULL_REQUEST_NAME: ${{ inputs.pull_request_name }}
        INPUTS_RELEASE_NAME: ${{ inputs.release_name }}
        AWS_REGION: ${{ inputs.aws_region }}
        AWS_STS_ROLE_ARN: ${{ inputs.aws_sts_role_arn }}
      run: |
        printf "%s\n" \
          "environment: preview/${INPUTS_PULL_REQUEST_NAME}" \
          "release_name: ${INPUTS_RELEASE_NAME}" \
          "default:" \
          "  region: ${AWS_REGION}" \
          "  sts_role_arn: ${AWS_STS_ROLE_ARN}" \
          > global-inputs.yaml

    - name: Generate state_conf.yaml from vars.DEPLOYMENT_STATE_CONF
      working-directory: ${{ inputs.blueprint_path }}/terraform/azure
      shell: bash
      env:
        INPUTS_TERRAFORM_STATE_CONF: ${{ inputs.terraform_state_conf }}
      run: |
        printf "%s\n" "${INPUTS_TERRAFORM_STATE_CONF}" > state_conf.yaml

    - name: Determine Plan Action
      uses: actions/github-script@v8
      id: plan_action
      env:
        INPUTS_DESTROY: ${{ inputs.destroy }}
        INPUTS_UNLOCK: ${{ inputs.unlock }}
        INPUTS_LOCK_ID: ${{ inputs.lock_id }}
      with:
        script: |
          const is_destroy = ((process.env.INPUTS_DESTROY || '').toLowerCase() === 'true');
          const is_unlock = ((process.env.INPUTS_UNLOCK || '').toLowerCase() === 'true');
          if (is_destroy) {
            core.setOutput('value', 'plan -destroy -no-color -input=false')
            console.log('destroy');
          } else {
            if (is_unlock) {
              core.setOutput('value', 'force-unlock -force ' + (process.env.INPUTS_LOCK_ID || '') + '')
              console.log('unlock');
            } else {
              core.setOutput('value', 'plan -no-color -input=false')
              console.log('apply');
            }
          }

    - name: Terragrunt Plan
      id: plan
      working-directory: ${{ inputs.blueprint_path }}/terraform/azure/kubernetes
      shell: bash
      env:
        STEPS_PLAN_ACTION_VALUE: ${{ steps.plan_action.outputs.value }}
        TG_TF_PATH: tofu
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        HELM_CREDS_USER: ${{ inputs.aws_access_key_id }}
        HELM_CREDS_PASSWORD: ${{ inputs.aws_secret_access_key }}
        HELM_EXPERIMENTAL_OCI: "1"
        GITHUB_API_TOKEN: ${{ inputs.token }}
      run: |
        echo "::group::Terragrunt Plan"
        terragrunt --non-interactive run -- ${STEPS_PLAN_ACTION_VALUE}
        echo "::endgroup::"
    - name: Terragrunt Plan to JSON
      working-directory: ${{ inputs.blueprint_path }}/terraform/azure/kubernetes
      if: ${{ inputs.unlock != 'true' }}
      shell: bash
      run: |
        echo "::group::Terragrunt Plan to JSON"
        terragrunt --non-interactive run -- show -json plan.tfplan > tfplan.json
        echo "::endgroup::"
      env:
        TG_TF_PATH: tofu
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        GITHUB_API_TOKEN: ${{ inputs.token }}

    - name: TF Summarize of JSON file
      working-directory: ${{ inputs.blueprint_path }}/terraform/azure/kubernetes
      if: ${{ inputs.unlock != 'true' }}
      shell: bash
      run: |
        echo "::group::TF Summarize of JSON file"
        tf-summarize tfplan.json
        echo "::endgroup::"

    - name: Terragrunt Apply
      id: apply
      working-directory: ${{ inputs.blueprint_path }}/terraform/azure/kubernetes
      shell: bash
      run: |
        echo "::group::Terragrunt Apply"
        terragrunt --non-interactive run -- apply -no-color plan.tfplan
        echo "::endgroup::"
      continue-on-error: false
      env:
        TG_TF_PATH: tofu
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        HELM_CREDS_USER: ${{ inputs.aws_access_key_id }}
        HELM_CREDS_PASSWORD: ${{ inputs.aws_secret_access_key }}
        HELM_EXPERIMENTAL_OCI: "1"
        GITHUB_API_TOKEN: ${{ inputs.token }}

