##
# (c) 2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Deploy .Net Component
author: cloudopsworks
description: Deploy .Net component to .Net repository
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  artifacts_name:
    description: 'The name of the artifacts to save'
    required: false
    default: 'build_artifacts'
  sources_artifacts_name:
    description: 'The name of the sources to save'
    required: false
    default: 'source_artifacts'
  bot_user:
    description: 'The bot user to use for the build'
    required: true
  token:
    description: 'The github token to use for the build'
    required: true

runs:
  using: 'composite'
  steps:
    # Get if this is a library project
    - name: Get pipeline is_library enabled
      id: is_library
      uses: mikefarah/yq@master
      with:
        cmd: yq e '.isLibrary and true' ./${{ inputs.source_path }}/.github/vars/inputs-global.yaml

    # Deploy release to .Net Repository (defaults to Github repo)
    - name: Register to NuGet Repo
      if: ${{ steps.is_library.outputs.result == 'true' }}
      working-directory: ${{ inputs.source_path }}
      shell: bash
      run: |
        echo "::group::.Net Register to NuGet Repo"        
        dotnet nuget add source --username $GITHUB_ACTOR --password $GITHUB_TOKEN --store-password-in-clear-text --name nuget "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        echo "::endgroup::"
      env:
        GITHUB_ACTOR: ${{ inputs.bot_user }}
        GITHUB_TOKEN: ${{ inputs.token }}
