{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  {{- if .Values.gateway.name }}
  name: {{ .Values.gateway.name }}
  {{- else }}
  name: {{ template "fullname" . }}
  {{- end }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- with .Values.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName | quote }}
  {{- with .Values.gateway.addresses }}
  addresses:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.gateway.listeners }}
  listeners:
    {{- range $name, $listener := .Values.gateway.listeners }}
    - name: {{ $name }}
      {{- if not $listener.hostname }}
      {{- if $.Values.gateway.host }}
      hostname: {{ $.Values.gateway.host }}
      {{- end }}
      {{- end }}
      {{- toYaml $listener | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
