##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Process Owners action
author: cloudopsworks
description: Process Owners (cloudopsworks-ci.yaml) and configure pipeline/repository
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  token:
    description: 'The GitHub token'
    required: true
  bot_user:
    description: 'The bot user to use for the build'
    required: true
  bot_email:
    description: 'The bot email to use for the build'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Retrieve branch protection rule
      id: branch_protection_rules
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        RET=$(yq e ".config.branchProtection and true" .cloudopsworks/cloudopsworks-ci.yaml)
        echo "result=${RET}" >> ${GITHUB_OUTPUT}

    - name: Retrieve Conventional Commits ruleset
      id: conventional_commits
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        RET=$(yq e ".config.conventionalCommitsEnabled and true" .cloudopsworks/cloudopsworks-ci.yaml)
        echo "result=${RET}" >> $GITHUB_OUTPUT

    - name: Retrieve Conventional Commits enforcement
      id: enforce_conventional_commits
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        RET=$(yq e ".config.enforceConventionalCommits and true" .cloudopsworks/cloudopsworks-ci.yaml)
        echo "result=${RET}" >> $GITHUB_OUTPUT

    - name: Retrieve Custom Commits Pattern Enforcement
      id: custom_commits_pattern
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        RET=$(yq e ".config.enforceCustomCommitsPattern and true" .cloudopsworks/cloudopsworks-ci.yaml)
        echo "result=${RET}" >> $GITHUB_OUTPUT

    - name: Retrieve Custom Commits Enforcement Pattern
      id: custom_commits_pattern_regex
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        RET=$(yq e ".config.enforceCustomCommitsPatternRegex" .cloudopsworks/cloudopsworks-ci.yaml)
        echo "result=${RET}" >> $GITHUB_OUTPUT

    - name: Retrieve protected sources
      id: protected_sources
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        RET=$(yq -o=json -I=0 ".config.protectedSources" .cloudopsworks/cloudopsworks-ci.yaml)
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> $GITHUB_OUTPUT

    - name: Check if automatic
      id: check_automatic
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        RET=$(yq e ".cd.automatic and true" .cloudopsworks/cloudopsworks-ci.yaml)
        echo "result=${RET}" >> $GITHUB_OUTPUT

    - name: Reviewers Count
      id: reviewers_count
      if: ${{ steps.check_automatic.outputs.result == 'true' || steps.branch_protection_rules.outputs.result == 'true' }}
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        RET=$(yq e ".config.requiredReviewers" .cloudopsworks/cloudopsworks-ci.yaml)
        echo "result=${RET}" >> $GITHUB_OUTPUT

    - name: Reviewers list as JSON
      id: reviewers_list
      if: ${{ steps.check_automatic.outputs.result == 'true' || steps.branch_protection_rules.outputs.result == 'true' }}
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        RET=$(yq -o=json -I=0 ".config.reviewers" .cloudopsworks/cloudopsworks-ci.yaml)
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"

    - name: Owners list as JSON
      id: owners_list
      if: ${{ steps.check_automatic.outputs.result == 'true' || steps.branch_protection_rules.outputs.result == 'true' }}
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        RET=$(yq -o=json -I=0 ".config.owners" .cloudopsworks/cloudopsworks-ci.yaml)
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"

    - name: Contributors list as JSON
      id: contrib_list
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        RET=$(yq -o=json -I=0 ".config.contributors" .cloudopsworks/cloudopsworks-ci.yaml)
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"

    - name: Deployments JSON
      id: deployments_json
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        RET=$(yq -o=json -I=0 ".cd.deployments" .cloudopsworks/cloudopsworks-ci.yaml)
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"

    - name: Get repository type
      id: repo_type
      working-directory: ${{ inputs.source_path }}
      shell: bash
      run: |
        if [ -f .cloudopsworks/.iac ]; then
          echo "result=iac" >> $GITHUB_OUTPUT
        elif [ -f .cloudopsworks/.docker ]; then
          echo "result=dockeronly" >> $GITHUB_OUTPUT
        else
          echo "result=sourcecode" >> $GITHUB_OUTPUT
        fi

    - name: Contributor list form JSON
      uses: cloudopsworks/blueprints/cd/tasks/repo/owners/contributors@v5.10
      with:
        token: ${{ inputs.token }}
        contrib_list: ${{ steps.contrib_list.outputs.result }}

    - name: Advanced Protection on GitFlow
      if: ${{ steps.branch_protection_rules.outputs.result == 'true' }}
      uses: cloudopsworks/blueprints/cd/tasks/repo/owners/protect/gitflow@v5.10
      with:
        token: ${{ inputs.token }}
        reviewers_list: ${{ steps.reviewers_list.outputs.result }}
        owners_list: ${{ steps.owners_list.outputs.result }}
        contrib_list: ${{ steps.contrib_list.outputs.result }}
        reviewers_count: ${{ steps.reviewers_count.outputs.result }}
        repo_type: ${{ steps.repo_type.outputs.result }}

    - name: Rulesets for Conventional commits
      if: ${{ steps.branch_protection_rules.outputs.result == 'true' && steps.conventional_commits.outputs.result == 'true' }}
      uses: cloudopsworks/blueprints/cd/tasks/repo/owners/protect/commits@v5.10
      with:
        reviewers_list: ${{ steps.reviewers_list.outputs.result }}
        owners_list: ${{ steps.owners_list.outputs.result }}
        contrib_list: ${{ steps.contrib_list.outputs.result }}
        reviewers_count: ${{ steps.reviewers_count.outputs.result }}
        repo_type: ${{ steps.repo_type.outputs.result }}
        enforce_conventional_commits: ${{ steps.enforce_conventional_commits.outputs.result }}
        custom_commits_pattern: ${{ steps.custom_commits_pattern.outputs.result }}
        custom_commits_pattern_regex: ${{ steps.custom_commits_pattern_regex.outputs.result }}


    - name: Rulesets for Protected Sources
      if: ${{ steps.branch_protection_rules.outputs.result == 'true' }}
      uses: cloudopsworks/blueprints/cd/tasks/repo/owners/protect/sources@v5.10
      with:
        token: ${{ inputs.token }}
        protected_sources: ${{ steps.protected_sources.outputs.result }}
        reviewers_list: ${{ steps.reviewers_list.outputs.result }}
        owners_list: ${{ steps.owners_list.outputs.result }}

    - name: Advanced Deployment Environments Creation
      id: envs
      uses: cloudopsworks/blueprints/cd/tasks/repo/owners/envs@v5.10
      with:
        token: ${{ inputs.token }}
        reviewers_list: ${{ steps.reviewers_list.outputs.result }}
        deployments_json: ${{ steps.deployments_json.outputs.result }}
        source_path: ${{ inputs.source_path }}
