##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Bucket Config retrieval
author: cloudopsworks
description: Retrieve the bucket configuration
inputs:
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  cloud:
    description: 'The target cloud'
    required: true
  cloud_type:
    description: 'The target cloud type'
    required: true
  environment:
    description: 'The environment'
    required: true
outputs:
  versions_bucket:
    description: 'The versions bucket'
    value: ${{ steps.versions_bucket.outputs.result }}
  bucket_path:
    description: 'The bucket path'
    value: ${{ steps.bucket_path.outputs.result }}

runs:
  using: 'composite'
  steps:
    - name: Get Bucket Name from inputs-${{ inputs.environment }}.yaml
      id: versions_bucket
      working-directory: ${{ inputs.blueprint_path }}/terraform/${{ inputs.cloud }}/${{ inputs.cloud_type }}
      shell: bash
      run: |
        VAL=$(yq eval '.versions_bucket' inputs.yaml)
        echo "result=$VAL" >> $GITHUB_OUTPUT

    - name: Get Bucket Name form release.yaml
      id: bucket_path
      working-directory: ${{ inputs.blueprint_path }}/terraform/${{ inputs.cloud }}/${{ inputs.cloud_type }}
      shell: bash
      run: |
        VAL=$(yq eval '.bucket_path' release.yaml)
        echo "result=$VAL" >> $GITHUB_OUTPUT
