##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Generate Containerized .Net Application
author: cloudopsworks
description: Generate a containerized .Net application
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  semver:
    description: 'The semver version to use for the build'
    required: true
  dotnet_version:
    description: 'The .Net version to use for the build'
    required: true
  dotnet_dist:
    description: 'The .Net distribution to use for the build'
    required: true
  dotnet_image_variant:
    description: 'The .Net image variant to use for the build'
    required: true
  environment:
    description: 'The environment to use for the build'
    required: true
  package_name:
    description: 'The package name'
    required: true
  is_release:
    description: 'The release flag'
    required: true
  default_registry_address:
    description: 'The default registry'
    required: true
  project_key:
    description: 'The project name key'
    required: true
  project_owner:
    description: 'The project owner'
    required: true
  observability_enabled:
    description: 'The observability flag'
    required: false
    default: 'false'
  observability_agent:
    description: 'The observability agent'
    required: false
    default: 'xray'

runs:
  using: 'composite'
  steps:
    # Recover the docker_registry value from the environment file
    - name: Get Docker Registry value if set into the ENV file
      id: docker_registry
      shell: bash
      env:
        INPUTS_DEFAULT_REGISTRY_ADDRESS: ${{ inputs.default_registry_address }}
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
        INPUTS_ENVIRONMENT: ${{ inputs.environment }}
      run: |
        RET=$(yq -I=0 ".container_registry // strenv(INPUTS_DEFAULT_REGISTRY_ADDRESS)" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-${INPUTS_ENVIRONMENT}.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Docker Inline Setting
      id: docker_inline
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 ".docker_inline // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Docker Arguments
      id: docker_args_global
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 ".docker_args // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Docker Arguments for ${{ inputs.environment }}
      id: docker_args_env
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
        INPUTS_ENVIRONMENT: ${{ inputs.environment }}
      run: |
        RET=$(yq e -I=0 ".docker_args // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-${INPUTS_ENVIRONMENT}.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Custom Run Command
      id: custom_run_command
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 ".custom_run_command // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get Custom Usergroup
      id: custom_usergroup
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 ".custom_usergroup // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Copy Dockerfile .Net App
      shell: bash
      env:
        INPUTS_BLUEPRINT_PATH: ${{ inputs.blueprint_path }}
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        cp -pf "${INPUTS_BLUEPRINT_PATH}/ci/container/blueprints/dotnet/"* "${INPUTS_SOURCE_PATH}/"
        cp -pf "${INPUTS_BLUEPRINT_PATH}/ci/container/blueprints/dotnet/.dockerignore" "${INPUTS_SOURCE_PATH}/"

    - name: Get default config_map mount point for environment
      id: config_map_mount_point
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
        INPUTS_ENVIRONMENT: ${{ inputs.environment }}
      run: |
        RET=$(yq e -I=0 ".config_map.mount_point // \"/app/configmap\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-${INPUTS_ENVIRONMENT}.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Get xray config file from inputs-global.yaml
      id: xray_config_file
      if: ${{ inputs.observability_enabled == 'true' && inputs.observability_agent == 'xray' }}
      shell: bash
      env:
        STEPS_CONFIG_MAP_MOUNT_POINT_RESULT: ${{ steps.config_map_mount_point.outputs.result }}
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e -I=0 "(.observability.config.configFilePath // strenv(STEPS_CONFIG_MAP_MOUNT_POINT_RESULT)) + \"/\" + (.observability.config.configFileName // \"xray-agent.json\")" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        {
          echo "result<<EOF"
          echo "${RET}"
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"
    - name: Download AWS Xray agent
      if: ${{ inputs.observability_enabled == 'true' && inputs.observability_agent == 'xray' }}
      shell: bash
      working-directory: ${{ inputs.source_path }}
      run: |
        tmpdir=$(mktemp -d)
        mkdir -p observability/
        #curl -Lo $tmpdir/aws-opentelemetry-agent.zip https://github.com/aws-observability/aws-otel-dotnet-instrumentation/releases/latest/download/aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip
        #unzip $tmpdir/aws-opentelemetry-agent.zip -d observability/
        

    - name: Dockerfile .Net Specific Injection
      working-directory: ${{ inputs.source_path }}
      shell: bash
      env:
        INPUTS_OBSERVABILITY_ENABLED: ${{ inputs.observability_enabled }}
        INPUTS_OBSERVABILITY_AGENT: ${{ inputs.observability_agent }}
        INPUTS_DOCKER_INLINE: ${{ inputs.docker_inline }}
      run: |
        echo "::group::Injecting .Net content in Dockerfile..."
        DOCKERFILE=Dockerfile
        TEMP_FILE=$(mktemp)
        INJECTION_POINT="#<DOTNET-INJECTION-POINT>"
        while IFS= read -r line; do
          if [[ "$line" =~ $INJECTION_POINT ]]; then
            # Insert the content related to observability agent installation
            if [ "${INPUTS_OBSERVABILITY_ENABLED}" == "true" ]; then
              case "${INPUTS_OBSERVABILITY_AGENT}" in
                xray)
                  echo "RUN curl -sL https://github.com/aws-observability/aws-otel-dotnet-instrumentation/releases/latest/download/aws-otel-dotnet-install.sh | bash"
                  ;;
                datadog)
                  echo "ADD 'https://github.com/DataDog/dd-trace-dotnet/releases/download/v3.16.0/datadog-dotnet-apm-3.16.0-musl.tar.gz' /opt/datadog/"
                  echo "RUN mkdir -p /var/log/datadog/dotnet/"
                  echo "RUN chown $USER_NAME:$GROUP_NAME /var/log/datadog/dotnet/"
                  ;;
              esac
            fi
            # Insert the Application Content at the injection point
            echo "COPY PublishRelease/* /app/webapp/"
            echo "${INPUTS_DOCKER_INLINE}"
          else
            # Print the current line
            echo "$line"
          fi
        done < "$DOCKERFILE" > "$TEMP_FILE"
        mv "$TEMP_FILE" "$DOCKERFILE"
        cat "$DOCKERFILE"
        echo "::endgroup::"

    # .Net version image settings (adopt is deprecated)
    - name: Set output with .Net Version
      id: docker_image_name
      shell: bash
      env:
        INPUTS_DOTNET_VERSION: ${{ inputs.dotnet_version }}
        INPUTS_DOTNET_DIST: ${{ inputs.dotnet_dist }}
        INPUTS_DOTNET_IMAGE_VARIANT: ${{ inputs.dotnet_image_variant }}
      run: |
        if [ "${INPUTS_DOTNET_VERSION}" != "" ] ; then
          echo "result=IMAGE_NAME=mcr.microsoft.com/dotnet/${INPUTS_DOTNET_DIST}:${INPUTS_DOTNET_VERSION}-${INPUTS_DOTNET_IMAGE_VARIANT}" >> $GITHUB_OUTPUT
        else
          echo "::error::dotnet_version is blank!"
          exit 1
        fi

    # if custom_run_command is non empty then need to override the startup.sh scripts with new content, write the file in-place
    - name: Set custom run command
      working-directory: ${{ inputs.source_path }}
      if: ${{ steps.custom_run_command.outputs.result != '' }}
      shell: bash
      run: |
        echo "Creation of custom startup.sh script..."
        cat > ./startup.sh << EOF
        #!/bin/sh
        
        # Startup the .Net App (custom command)
        cd /app/webapp
        $CUSTOM_RUN_COMMAND
        EOF
        cat ./startup.sh
      env:
        CUSTOM_RUN_COMMAND: ${{ steps.custom_run_command.outputs.result }}

    - name: Build and set startup.sh command
      if: ${{ steps.custom_run_command.outputs.result == '' }}
      working-directory: ${{ inputs.source_path }}
      shell: bash
      env:
        INPUTS_PACKAGE_NAME: ${{ inputs.package_name }}
      run: |
        echo "Creation of startup.sh script..."
        cat > ./startup.sh << EOF
        #!/bin/sh
        
        # Startup the .Net App
        cd /app/webapp
        exec dotnet ${INPUTS_PACKAGE_NAME}.dll \${DOTNET_ARGS}
        EOF
        cat ./startup.sh
        

    # Run Generalized Docker Build & Upload Artifact
    - name: Generalized Docker Build
      uses: ./bp/ci/container/build
      with:
        semver: ${{ inputs.semver }}
        docker_registry: ${{ steps.docker_registry.outputs.result }}
        docker_inline: ${{ steps.docker_inline.outputs.result }}
        docker_image_name: ${{ steps.docker_image_name.outputs.result }}
        docker_args: ${{ steps.docker_args_env.outputs.result == '' && steps.docker_args_global.outputs.result || steps.docker_args_env.outputs.result }}
        apm_args: ${{ inputs.observability_enabled == 'true' && steps.apm_args.outputs.result || '' }}
        environment: ${{ inputs.environment }}
        project_key: ${{ inputs.project_key }}
        project_owner: ${{ inputs.project_owner }}
        custom_usergroup: ${{ steps.custom_usergroup.outputs.result }}
        is_release: ${{ inputs.is_release }}
