{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  {{- if .Values.service.name }}
  name: {{ .Values.service.name }}
  {{- else }}
  name: {{ template "fullname" . }}
  {{- end }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    {{- if .Values.service.name }}
    name: {{ .Values.service.name }}
    {{- else }}
    name: {{ template "fullname" . }}
    {{- end }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  behavior:
    scaleDown:
      {{- if .Values.hpa.scaleDown }}
      {{- toYaml .Values.hpa.scaleDown | nindent 6 }}
      {{- else }}
      stabilizationWindowSeconds: {{ .Values.hpa.stabilizationWindowSeconds | default "300" }}
      policies:
        - type: Percent
          value: {{ .Values.hpa.percentValueDown | default "40" }}
          periodSeconds: {{ .Values.hpa.percentPeriodDown | default "60" }}
      {{- end }}
    scaleUp:
      {{- if .Values.hpa.scaleUp }}
      {{- toYaml .Values.hpa.scaleUp | nindent 6 }}
      {{- else }}
      stabilizationWindowSeconds: {{ .Values.hpa.stabilizationWindowSeconds | default "300" }}
      policies:
        - type: Percent
          value: {{ .Values.hpa.percentValueUp | default "80" }}
          periodSeconds: {{ .Values.hpa.percentPeriodUp | default "60" }}
      {{- end }}
  metrics:
  {{- if .Values.hpa.external.enabled }}
    - type: External
      external:
        metric:
          name: {{ .Values.hpa.external.name }}
          {{- with .Values.hpa.external.labelSelector }}
          selector:
            matchLabels:
              {{- toYaml . | nindent 14 }}
          {{- end }}
        target:
          type: AverageValue
          averageValue: {{ .Values.hpa.external.averageValue }}
  {{- else }}
    {{- if .Values.hpa.cpuPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
            type: Utilization
            averageUtilization: {{ .Values.hpa.cpuTargetAverageUtilization | default "80" }}
    {{- end }}
    {{- if .Values.hpa.memoryPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.memoryTargetAverageUtilization | default "80" }}
    {{- end }}
    {{- if values.hpa.metrics }}
    {{- toYaml .Values.hpa.metrics | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}