{{- if and .Values.ingress.enabled .Values.service.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.service.name }}
  name: {{ .Values.service.name }}
  {{- else }}
  name: {{ template "fullname" . }}
  {{- end }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName -}}
  {{- end }}
  {{- with .Values.ingress.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- if .Values.ingress.host }}
        - {{ .Values.ingress.host }}
      {{- else if .Values.service.name }}
        - {{ .Values.service.name }}
      {{- else }}
        - {{ template "fullname" . }}
      {{- end }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: "{{ .Values.ingress.tls.secretName }}"
      {{- else }}
      secretName: "tls-{{ template "fullname" . }}-s"
      {{- end }}
  {{- end }}
{{- end }}