{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.service.name }}
  name: {{ .Values.service.name }}
  {{- else }}
  name: {{ template "fullname" . }}
  {{- end }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.secret.values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end}}