{{- if not .Values.cronjob.enabled }}
{{- if not .Values.job.enabled }}
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.name }}
  name: {{ .Values.service.name }}
  {{- else }}
  name: {{ template "fullname" . }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  {{- with .Values.service.extraPorts }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    app: {{ template "fullname" . }}
{{- end }}
{{- end }}
{{- end }}