##
# (c) 2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Push TAG
author: cloudopsworks
description: Push TAG into repository
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  token:
    description: 'The GitHub token'
    required: true
  bot_user:
    description: 'The bot user'
    required: true
  bot_email:
    description: 'The bot email'
    required: true

runs:
  using: 'composite'
  steps:
    # Push the changes to Git TAG before deploying anything
    - name: Push TAG
      working-directory: ${{ inputs.source_path }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        git config --global user.name "${{ inputs.bot_user }}"
        git config --global user.email "${{ inputs.bot_email}}"
        git pull --rebase
        make gitflow/version/tag
        make gitflow/version/publish
