##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Generate Containerized GoLang Application
author: cloudopsworks
description: Generate a containerized GoLang application
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  semver:
    description: 'The semver version to use for the build'
    required: true
  golang_version:
    description: 'The GoLang version to use for the build'
    required: true
  golang_dist:
    description: 'The GoLang distribution to use for the build'
    required: true
  golang_arch:
    description: 'The GoLang architecture to use for the build'
    required: true
  golang_image_variant:
    description: 'The GoLang image variant to use for the build'
    required: true
  environment:
    description: 'The environment to use for the build'
    required: true
  package_name:
    description: 'The package name'
    required: true
  is_release:
    description: 'The release flag'
    required: true
  default_registry_address:
    description: 'The default registry'
    required: true
  project_key:
    description: 'The project name key'
    required: true
  project_owner:
    description: 'The project owner'
    required: true
  observability_enabled:
    description: 'The observability flag'
    required: false
    default: 'false'
  observability_agent:
    description: 'The observability agent'
    required: false
    default: 'xray'

runs:
  using: 'composite'
  steps:
    # Recover the docker_registry value from the environment file
    - name: Get Docker Registry value if set into the ENV file
      id: docker_registry
      uses: mikefarah/yq@master
      with:
        cmd: yq -I=0 '.container_registry // "${{ inputs.default_registry_address }}"' ./${{ inputs.source_path }}/.github/vars/inputs-${{ inputs.environment }}.yaml

    # get from global inputs the docker inline specification as text
    - name: Get Docker Inline Setting
      id: docker_inline
      uses: mikefarah/yq@master
      with:
        cmd: yq e -I=0 '.docker_inline // ""' ./${{ inputs.source_path }}/.github/vars/inputs-global.yaml

    # get from global inputs docker arguments, also as text
    - name: Get Docker Arguments
      id: docker_args_global
      uses: mikefarah/yq@master
      with:
        cmd: yq e -I=0 '.docker_args // ""' ./${{ inputs.source_path }}/.github/vars/inputs-global.yaml

    # get from environmental inputs the docker arguments will override the one set on docker_args,also as text
    - name: Get Docker Arguments for ${{ inputs.environment }}
      id: docker_args_env
      uses: mikefarah/yq@master
      with:
        cmd: yq e -I=0 '.docker_args // ""' ./${{ inputs.source_path }}/.github/vars/inputs-${{ inputs.environment }}.yaml

    # get custom_run_command from global inputs
    - name: Get Custom Run Command
      id: custom_run_command
      uses: mikefarah/yq@master
      with:
        cmd: yq e -I=0 '.custom_run_command // ""' ./${{ inputs.source_path }}/.github/vars/inputs-global.yaml

    # Get custom_usergroup Line item from configuration
    - name: Get Custom Usergroup
      id: custom_usergroup
      uses: mikefarah/yq@master
      with:
        cmd: yq e -I=0 '.custom_usergroup // ""' ./${{ inputs.source_path }}/.github/vars/inputs-global.yaml

    # Copy Dockerfile from blueprint to current dir
    - name: Copy Dockerfile GoLang App
      shell: bash
      run: |
        cp -pf ${{ inputs.blueprint_path }}/ci/container/blueprints/go/* ${{ inputs.source_path }}/
        cp -pf ${{ inputs.blueprint_path }}/ci/container/blueprints/go/.dockerignore ${{ inputs.source_path }}/

    - name: Get default config_map mount point for environment
      id: config_map_mount_point
      uses: mikefarah/yq@master
      with:
        cmd: yq e -I=0 '.config_map.mount_point // "/app/configmap"' ./${{ inputs.source_path }}/.github/vars/inputs-${{ inputs.environment }}.yaml

    - name: Get xray config file from inputs-global.yaml
      id: xray_config_file
      if: ${{ inputs.observability_enabled == 'true' && inputs.observability_agent == 'xray' }}
      uses: mikefarah/yq@master
      with:
        cmd: yq e -I=0 '.observability.config.configFilePath // "${{ steps.config_map_mount_point.outputs.result }}" + "/"  + .observability.config.configFileName // "xray-agent.json"' ./${{ inputs.source_path }}/.github/vars/inputs-global.yaml

    - name: Dockerfile GoLang Specific Injection
      working-directory: ${{ inputs.source_path }}
      shell: bash
      run: |
        echo "::group::Injecting GoLang content in Dockerfile..."
        DOCKERFILE=Dockerfile
        TEMP_FILE=$(mktemp)
        INJECTION_POINT="#<GOLANG-INJECTION-POINT>"
        while IFS= read -r line; do
          if [[ "$line" =~ $INJECTION_POINT ]]; then
            # Insert the content of input at the injection point depending on conditions
            echo "COPY bin/* /app/webapp/${{ inputs.project_key }}"
            echo "${{ inputs.docker_inline }}"
          else
            # Print the current line
            echo "$line"
          fi
        done < "$DOCKERFILE" > "$TEMP_FILE"
        mv "$TEMP_FILE" "$DOCKERFILE"
        cat "$DOCKERFILE"
        echo "::endgroup::"

    # GoLang version image settings (adopt is deprecated)
    - name: Set output with GoLang Version
      id: docker_image_name
      shell: bash
      run: |
        echo "result=IMAGE_NAME=${{ inputs.golang_image_variant }}" >> $GITHUB_OUTPUT

    # if custom_run_command is non empty then need to override the startup.sh scripts with new content, write the file in-place
    - name: Set custom run command
      working-directory: ${{ inputs.source_path }}
      if: ${{ steps.custom_run_command.outputs.result != '' }}
      shell: bash
      run: |
        echo "Creation of custom startup.sh script..."
        cat > ./startup.sh << EOF
        #!/bin/sh
        
        # Startup the GoLang App (custom command)
        cd /app/webapp
        $CUSTOM_RUN_COMMAND
        EOF
        cat ./startup.sh
      env:
        CUSTOM_RUN_COMMAND: ${{ steps.custom_run_command.outputs.result }}

    - name: Build and set startup.sh command
      if: ${{ steps.custom_run_command.outputs.result == '' }}
      working-directory: ${{ inputs.source_path }}
      shell: bash
      run: |
        echo "Creation of startup.sh script..."
        cat > ./startup.sh << EOF
        #!/bin/sh
        
        # Startup the .Net App
        cd /app/webapp
        exec bin/${{ inputs.package_name }} \${GOLANG_ARGS}
        EOF
        cat ./startup.sh
        

    # Run Generalized Docker Build & Upload Artifact
    - name: Generalized Docker Build
      uses: ./bp/ci/container/build
      with:
        semver: ${{ inputs.semver }}
        docker_registry: ${{ steps.docker_registry.outputs.result }}
        docker_inline: ${{ steps.docker_inline.outputs.result }}
        docker_image_name: ${{ steps.docker_image_name.outputs.result }}
        docker_args: ${{ steps.docker_args_env.outputs.result == '' && steps.docker_args_global.outputs.result || steps.docker_args_env.outputs.result }}
        apm_args: ${{ inputs.observability_enabled == 'true' && steps.apm_args.outputs.result || '' }}
        environment: ${{ inputs.environment }}
        project_key: ${{ inputs.project_key }}
        project_owner: ${{ inputs.project_owner }}
        custom_usergroup: ${{ steps.custom_usergroup.outputs.result }}
