##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Dependency Track Scan GoLang
author: cloudopsworks
description: This action scans the GoLang code using Dependency Track
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  dtrack_url:
      description: 'The Dependency Track URL'
      required: true
  dtrack_token:
      description: 'The Dependency Track token'
      required: true
  dtrack_project_key:
      description: 'The Dependency Track project key'
      required: true
  semver:
      description: 'The Semver version'
      required: true
  token:
      description: 'The Github token'
      required: true

runs:
  # TODO: DUPLICATE CODE with nodejs/dtrack/action.yml
  using: 'composite'
  steps:
    # SBOM upload
    - name: SBOM Dtrack Upload
      working-directory: ${{ inputs.source_path }}
      shell: bash
      run: |
        curl -X "POST" "https://${{ inputs.dtrack_url }}/api/v1/bom" \
             -H 'Content-Type: multipart/form-data' \
             -H 'X-API-Key: ${{ inputs.dtrack_token }}' \
             -F "autoCreate=true" \
             -F "projectName=${{ inputs.dtrack_project_key }}" \
             -F "projectVersion=${{ inputs.semver }}" \
             -F "parentName=${{ inputs.dtrack_project_key }}" \
             -F "bom=@target/bom.xml"
