##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Run Secrets Scan
author: cloudopsworks
description: |
  Runs Secret Scan security scans on Terraform code, will run scan with gitleaks and trufflehog,
  in order to detect secrets and sensitive information in the codebase.
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  trufflehog_version:
    description: 'The version of trufflehog to use for scanning'
    required: false
    default: 'v3.93.8'
  gitleaks_version:
    description: 'The version of gitleaks to use for scanning'
    required: false
    default: '8.30.0'
runs:
  using: 'composite'
  steps:
    - name: Download TruffleHog version
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin ${{ inputs.trufflehog_version }}

    - name: Download Gitleaks version
      shell: bash
      run: |
        # Determine platform (linux/darwin) and arch (amd64/arm64)
        PLATFORM=$(uname | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        if [[ "$ARCH" == "x86_64" ]]; then
          ARCH="x64"
        elif [[ "$ARCH" == "aarch64" ]]; then
          ARCH="arm64"
        else
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi
        # Download the appropriate gitleaks binary
        curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v${{ inputs.gitleaks_version }}/gitleaks_${{ inputs.gitleaks_version }}_${PLATFORM}_${ARCH}.tar.gz | tar -xz -C /usr/local/bin gitleaks

    - name: Run TruffleHog scan
      shell: bash
      id: trufflehog
      working-directory: ${{ inputs.source_path }}
      run: |
        trufflehog git --no-fail --no-color --json file://./ > trufflehog_results.json 

    - name: Run Gitleaks scan
      shell: bash
      id: gitleaks
      working-directory: ${{ inputs.source_path }}
      run: |
        gitleaks git -v --report-format sarif --report-path gitleaks_results.sarif --no-banner --no-color --exit-code 0 .

    - name: Upload Secret Scan results
      if: success() || failure()
      uses: actions/upload-artifact@v7
      with:
        name: secret-scan-results
        path: |
          ${{ inputs.source_path }}/trufflehog_results.json
          ${{ inputs.source_path }}/gitleaks_results.sarif

    - name: Upload GitLeaks SARIF file
      if: success() || steps.gitleaks.outcome == 'success'
      uses: github/codeql-action/upload-sarif@v4
      with:
        category: secrets
        sarif_file: ${{ inputs.source_path }}/gitleaks_results.sarif

#    - name: Upload TruffleHog JSON file
#      if: success() || steps.trufflehog.outcome == 'success'
#      uses: github/codeql-action/upload-sarif@v4
#      with:
#        category: secrets
#        sarif_file: ${{ inputs.source_path }}/trufflehog_results.json