##
# (c) 2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Xray Observability deployment setup for HELM
author: cloudopsworks
description: Xray Observability deployment setup for HELM chart
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  cloud:
    description: 'The cloud'
    required: true
  release_name:
    description: 'The release name'
    required: true
  release_version:
    description: 'The release version'
    required: true
  project_key:
    description: 'The package name'
    required: true
  deployment_name:
    description: 'The deployment name'
    required: true
  environment:
    description: 'The environment'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Xray variable Injection
      working-directory: ${{ inputs.blueprint_path }}/terraform/aws/kubernetes
      id: xray_inject
      shell: bash
      run: |
        echo "::group::Xray variable Injection"
        yq e -i '.config_map.enabled = true' inputs.yaml
        yq e -i '.env += [{"name":"OTEL_RESOURCE_ATTRIBUTES","value":"service.name=${{ inputs.release_name }},service.version=${{ inputs.release_version }},service.env=${{ inputs.environment }},service.sourceProject=${{ inputs.project_key }}"}]' helm-values.yaml
        echo "::endgroup::"
