##
# (c) 2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: SonarQube Scan Quality Gate Status
author: cloudopsworks
description: |
  This action checks the SonarQube Quality Gate status, it will fail
  if the condition is met based on the Quality Gate status.
  failure can be omitted if configured so
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  sonarqube_url:
    description: 'The Sonarqube URL'
    required: true
  sonarqube_token:
    description: 'The Sonarqube token'
    required: true
outputs:
  quality_gate_status:
    description: 'The Quality Gate status'
    value: ${{ steps.sonarqube_quality_gate_status.outputs.quality_gate_status }}

runs:
  using: 'composite'
  steps:
    - run: ls -lRa .
      shell: bash
    - name: Sonar Scan Quality Gate Status
      uses: sonarsource/sonarqube-quality-gate-action@master
      env:
        SONAR_TOKEN: ${{ inputs.sonarqube_token }}
        SONAR_HOST_URL: ${{ inputs.sonarqube_url }}
      with:
        scanMetadataReportFile: ${{ inputs.source_path }}/target/sonar/report-task.txt

