##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Release Workflow for GoReleaser pipeline
author: cloudopsworks
description: Release Workflow for GoReleaser pipeline
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  token:
    description: 'The github token to use for the release'
    required: true
  gpg_private_key:
    description: 'The GPG private key to use for signing the release'
    required: true
  gpg_passphrase:
    description: 'The GPG passphrase to use for signing the release'
    required: true
  semver:
    description: 'The semver version to use for the release'
    required: true
  golang_version:
    description: 'The GoLang version to use for the release'
    required: true
  homebrew_tap_token:
    description: 'The github token to use for the homebrew tap release, comes from secret: HOMEBREW_TAP_TOKEN'
    required: false
    default: ''
  chocolatey_api_key:
    description: 'The chocolatey api key to use for the chocolatey release, comes from secret: CHOCOLATEY_API_KEY'
    required: false
    default: ''
  apple_certificate_b64:
    description: 'The Apple certificate in base64 format to use for signing the release, comes from secret: XCODE_BUILD_CERTIFICATE_BASE64'
    required: false
    default: ''
  apple_certificate_pass:
    description: 'The Apple certificate passphrase to use for signing the release, comes from secret: XCODE_BUILD_CERTIFICATE_PASS'
    required: false
    default: ''
  apple_store_connect_key_b64:
    description: 'The Apple Store Connect key in base64 format to use for signing the release, comes from secret: APPLE_STORE_CONNECT_KEY_BASE64'
    required: false
    default: ''
  apple_store_connect_key_id:
    description: 'The Apple Store Connect key id to use for signing the release, comes from secret: APPLE_STORE_CONNECT_KEY_ID'
    required: false
    default: ''
  apple_store_connect_issuer_id:
    description: 'The Apple Store Connect issuer id to use for signing the release, comes from secret: APPLE_STORE_CONNECT_ISSUER_ID'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        token: ${{ inputs.token }}
        go-version: ${{ inputs.golang_version }}
        go-version-file: ${{ inputs.source_path }}/go.mod
        check-latest: true
        cache: true

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v7
      with:
        gpg_private_key: ${{ inputs.gpg_private_key }}
        passphrase: ${{ inputs.gpg_passphrase }}

    - name: Cleanup for goreleaser
      working-directory: ${{ inputs.source_path }}
      shell: bash
      run: |
        git clean -df

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v7
      with:
        workdir: ${{ inputs.source_path }}
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        PASSPHRASE: ${{ inputs.gpg_passphrase }}
        HOMEBREW_TAP_TOKEN: ${{ inputs.homebrew_tap_token }}
        CHOCOLATEY_API_KEY: ${{ inputs.chocolatey_api_key }}
        MACOS_SIGN_P12: ${{ inputs.apple_certificate_b64 }}
        MACOS_SIGN_PASSWORD: ${{ inputs.apple_certificate_pass }}
        MACOS_NOTARY_ISSUER_ID: ${{ inputs.apple_store_connect_issuer_id }}
        MACOS_NOTARY_KEY_ID: ${{ inputs.apple_store_connect_key_id }}
        MACOS_NOTARY_KEY: ${{ inputs.apple_store_connect_key_b64 }}
