##
# (c) 2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Save Python Artifacts
author: cloudopsworks
description: Save Python artifacts to the artifacts store
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  artifacts_name:
    description: 'The name of the artifacts to save'
    required: false
    default: 'build_artifacts'
  sources_artifacts_name:
    description: 'The name of the sources to save'
    required: false
    default: 'source_artifacts'

runs:
  using: 'composite'
  steps:
    # Get pipeline conf
    - name: Get pipeline zip packaging globs
      id: zip_globs
      uses: mikefarah/yq@master
      with:
        cmd: yq e '.zipGlobs[] | "${{ inputs.source_path }}/" + .' ./${{ inputs.source_path }}/.github/cloudopsworks-ci.yaml

    # Get pipeline conf exclude globs
    - name: Get pipeline zip packaging exclude globs
      id: exclude_globs
      uses: mikefarah/yq@master
      with:
        cmd: yq e '.excludeGlobs[] | "!${{ inputs.source_path }}/" + .' ./${{ inputs.source_path }}/.github/cloudopsworks-ci.yaml

    # Perform of upload of artfiacts for python with dependencies if file exists
    - name: Upload Artifacts to workflow
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifacts_name }}
        path: |
          ${{ steps.zip_globs.outputs.result }}
          ${{ inputs.source_path }}/python-dependencies.tar
          ${{ steps.exclude_globs.outputs.result }}
        retention-days: 1
        include-hidden-files: true
        compression-level: '1' #fast
        overwrite: 'true'

    # Perform of upload of sources
    - name: Upload Sources to workflow
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.sources_artifacts_name }}
        path: |
          ${{ inputs.source_path }}/app/**
          !${{ inputs.source_path }}/target/**
          ${{ steps.exclude_globs.outputs.result }}
        retention-days: 1
        include-hidden-files: true
        compression-level: '3' #mid-fast

    # Perform of upload of all target artfiacts for Python
    - name: Upload Target Artifacts to workflow
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.sources_artifacts_name }}_target
        path: |
          ${{ steps.zip_globs.outputs.result }}
          ${{ inputs.source_path }}/bom.xml
          ${{ inputs.source_path }}/.coverage
          ${{ inputs.source_path }}/coverage.xml
          ${{ inputs.source_path }}/test-results.xml
          ${{ inputs.source_path }}/htmlcov/**/*
          ${{ inputs.source_path }}/__tests__/**/*
          ${{ inputs.source_path }}/ruff_report.json
          ${{ inputs.source_path }}/mypy_report.txt
        retention-days: 1
        include-hidden-files: true
        compression-level: '1' #fast
        overwrite: 'true'
