##
# (c) 2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Sonarqube Scan NodeJS
author: cloudopsworks
description: This action scans the Node.js code using Sonarqube
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  sonarqube_url:
    description: 'The Sonarqube URL'
    required: true
  sonarqube_token:
    description: 'The Sonarqube token'
    required: true
  sonarqube_project_key:
    description: 'The Sonarqube project key'
    required: true
  semver:
    description: 'The Semver version'
    required: true
  token:
    description: 'The Github token'
    required: true

runs:
  using: 'composite'
  steps:
    # TODO: enable branch.name must buy Developer/Pro plan
    # Scan the code
    - name: Sonar Scan
      uses: sonarsource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ inputs.sonarqube_url }}
        SONAR_HOST_URL: ${{ inputs.sonarqube_token }}
      with:
        projectBaseDir: ${{ inputs.source_path }}
        args: >
          -Dsonar.projectKey=${{ inputs.sonarqube_project_key }}
          -Dsonar.projectVersion=${{ inputs.semver }}
          -Dsonar.sources=.
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.language=javascript
          -Dsonar.exclusions=node_modules/**,coverage/**,test/**,tests/**,charts/**,tronador/**,dist/**,build/**
          -Dsonar.tests=.
          -Dsonar.test.inclusions=**/*.test.js,**/*.spec.js
          -Dsonar.test.exclusions=node_modules/**,coverage/**,test/**,tests/**
#            -Dsonar.branch.name=${{ github.ref }}
