##
# (c) 2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Procfile creation for ElasticBeanstalk
author: cloudopsworks
description: Create Procfile for ElasticBeanstalk
inputs:
  temp_dir:
    description: 'The path to the blueprint'
    required: true
  java_stack:
    description: 'The Java stack'
    required: true
  node_stack:
    description: 'The Node stack'
    required: true
  python_stack:
    description: 'The Python stack'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Default Procfile for NodeJS
      if: ${{ inputs.node_stack == 'true' }}
      working-directory: ${{ inputs.temp_dir }}
      shell: bash
      run: |
        if [ ! -f Procfile ] ; then
          echo 'web: npm run start' > Procfile
          echo '::warning::Procfile created with default content'
        else
          echo '::notice::Procfile already exists, will use provided'
        fi

    - name: Default Procfile for Java
      if: ${{ inputs.java_stack == 'true' }}
      working-directory: ${{ inputs.temp_dir }}
      shell: bash
      run: |
        if [ ! -f Procfile ] ; then
          echo 'web: java $JAVA_OPTS -jar app.jar' > Procfile
          echo '::warning::Procfile created with default content'
        else
          echo '::notice::Procfile already exists, will use provided.'
        fi

