##
# (c) 2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Install Runner tools
author: cloudopsworks
description: Install runner-tools for the workflow

runs:
  using: 'composite'
  steps:
    - name: Install runner-tools
      working-directory: /tmp
      shell: bash
      run: |
        echo "::group::Install runner-tools"
        export DEBIAN_FRONTEND=noninteractive
        (type -p wget >/dev/null || (sudo apt update && sudo apt-get -y install wget))
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
        sudo apt install -y gh jq curl zip unzip python3 python3-pip apt-transport-https ca-certificates gnupg lsb-release
        echo "::endgroup::"

    - name: Download and Install AWS CLI
      working-directory: /tmp
      shell: bash
      run: |
        echo "::group::Download and install AWS CLI"
        curl -sL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -qo awscliv2.zip
        type -p aws > /dev/null || sudo ./aws/install
        type -p aws > /dev/null && sudo ./aws/install --update
        echo "::endgroup::"

    - name: Download and Install Azure CLI
      working-directory: /tmp
      shell: bash
      run: |
        echo "::group::Download and install Azure CLI"
        (type -p az > /dev/null || (echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ jammy main" | tee -a /etc/apt/sources.list.d/azure-cli.list && mkdir -p /etc/apt/keyrings && curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/keyrings/microsoft.gpg && chmod go+r /etc/apt/keyrings/microsoft.gpg && apt-get update -y && apt-get install azure-cli -y))
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ jammy main" | tee -a /etc/apt/sources.list.d/azure-cli.list && mkdir -p /etc/apt/keyrings && curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/keyrings/microsoft.gpg && chmod go+r /etc/apt/keyrings/microsoft.gpg && apt-get update -y && apt-get install azure-cli -y
        echo "::endgroup::"


    - name: Download and Install GCP CLI
      working-directory: /tmp
      shell: bash
      run: |
        echo "::group::Download and install GCP CLI"
        (type -p gcloud || (echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && apt-get update -y && apt-get install google-cloud-cli -y))
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && apt-get update -y && apt-get install google-cloud-cli -y
        echo "::endgroup::"