##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Install Runner tools
author: cloudopsworks
description: Install runner-tools for the workflow
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'

runs:
  using: 'composite'
  steps:
    - name: Platform Check with $RUNNER_OS
      id: platform
      shell: bash
      run: |
        plat=$(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')
        echo "Detected platform: $plat"
        echo "Run User: $(id)"
        echo "Sudoers: "
        cat /etc/sudoers
        echo "result=$plat" >> $GITHUB_OUTPUT

    - name: Install runner-tools - Linux
      uses: cloudopsworks/blueprints/ci/common/install/runner-tools/linux@v5.10
      if: ${{ steps.platform.outputs.result == 'linux' }}
      with:
        source_path: ${{ inputs.source_path }}

    - name: Install runner-tools - MacOS
      uses: cloudopsworks/blueprints/ci/common/install/runner-tools/macos@v5.10
      if: ${{ steps.platform.outputs.result == 'macos' }}
      with:
        source_path: ${{ inputs.source_path }}

    - name: Install runner-tools - Windows
      uses: cloudopsworks/blueprints/ci/common/install/runner-tools/windows@v5.10
      if: ${{ steps.platform.outputs.result == 'windows' }}
      with:
        source_path: ${{ inputs.source_path }}
