##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Copy APIs to blueprint
author: cloudopsworks
description: Copy APIs from source path to blueprint path
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  cloud:
    description: 'The cloud provider to use'
    required: true

runs:
  using: 'composite'
  steps:
    # Get api_files_dir from inputs-global.yaml
    - name: Get api_files_dir
      id: api_files_dir
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e ".api_files_dir // \"apifiles\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        echo "result=$RET" >> $GITHUB_OUTPUT

    # Get cloud provider from inputs-global.yaml
    - name: Get Cloud Provider
      id: cloud_provider
      shell: bash
      env:
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
      run: |
        RET=$(yq e ".cloud // \"\"" "./${INPUTS_SOURCE_PATH}/.cloudopsworks/vars/inputs-global.yaml")
        echo "result=$RET" >> $GITHUB_OUTPUT

    - name: Move Api Files
      shell: bash
      env:
        INPUTS_BLUEPRINT_PATH: ${{ inputs.blueprint_path }}
        STEPS_CLOUD_PROVIDER_RESULT: ${{ steps.cloud_provider.outputs.result }}
        INPUTS_SOURCE_PATH: ${{ inputs.source_path }}
        STEPS_API_FILES_DIR_RESULT: ${{ steps.api_files_dir.outputs.result }}
      run: |
        echo "Copying API files from source to blueprint..."
        mkdir -p "${INPUTS_BLUEPRINT_PATH}/terraform/${STEPS_CLOUD_PROVIDER_RESULT}/apigw/apifiles"
        cp -r "${INPUTS_SOURCE_PATH}/${STEPS_API_FILES_DIR_RESULT}/"* "${INPUTS_BLUEPRINT_PATH}/terraform/${STEPS_CLOUD_PROVIDER_RESULT}/apigw/apifiles/"
