##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Semgrep code Scanning Dockerfile
author: cloudopsworks
description: This action scans the Dockerfile using Semgrep and outputs the results in various formats.
inputs:
  source_path:
    description: 'The path to the source code'
    required: false
    default: 'source'
  blueprint_path:
    description: 'The path to the blueprint'
    required: false
    default: 'bp'
  bot_user:
    description: 'The bot user'
    required: true
  token:
    description: 'The Github token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download tarball image
      uses: actions/download-artifact@v7
      with:
        name: docker-image
        path: imagescan/

    - name: Manual Trivy Setup
      uses: aquasecurity/setup-trivy@v0.2.0
      with:
        cache: true
        version: v0.69.3

    - name: Run Trivy vulnerability scanner - sarif output
      uses: aquasecurity/trivy-action@0.35.0
      with:
        input: 'imagescan/docker-image.tar'
        format: 'json'
        output: 'trivy-results.json'
        skip-setup-trivy: true
        severity: 'CRITICAL,HIGH'
        github-pat: ${{ inputs.token }}

    - name: Run Trivy vulnerability scanner - sarif output
      uses: aquasecurity/trivy-action@0.35.0
      with:
        input: 'imagescan/docker-image.tar'
        format: 'sarif'
        skip-setup-trivy: true
        output: 'trivi-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'
        github-pat: ${{ inputs.token }}

    - name: Upload SARIF file
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: trivi-results.sarif
        wait-for-processing: false

